In [204]:
import numpy as np
import pandas as pd

In [205]:
df_train = pd.read_csv("./input/pose_angle_test_ffill.csv")
df_train

x_0        y_0   score_0        x_1        y_1   score_1  \
0     179.76530  60.258244  0.939276  180.39920  74.525390  0.850736   
1     179.77000  60.267480  0.938724  180.40907  74.522255  0.851064   
2     179.78280  60.261524  0.928379  180.40228  74.516790  0.843911   
3     180.40729  60.253990  0.913265  180.39053  73.890390  0.852116   
4     181.04353  60.265160  0.893009  181.68724  73.891525  0.812719   
...         ...        ...       ...        ...        ...       ...   
1256        NaN        NaN       NaN  169.38786  75.214836  0.911516   
1257        NaN        NaN       NaN  169.38457  75.211090  0.918276   
1258        NaN        NaN       NaN  169.39172  75.210556  0.914960   
1259        NaN        NaN       NaN  169.99731  75.206790  0.907052   
1260        NaN        NaN       NaN  170.00874  75.197660  0.886951   

            x_2        y_2   score_2        x_3  ...       x_22       y_22  \
0     169.99663  74.529175  0.809395  166.10310  ...  175.84912  169.35298   
1     170.00713  74.533250  0.823045  166.11751  ...  175.20096  169.38358   
2     169.99840  74.530780  0.818879  165.47404  ...  175.85600  169.38922   
3     169.37404  73.899300  0.814654  164.81367  ...  176.49518  169.38768   
4     170.66028  73.247660  0.785594  166.76718  ...  174.53969  170.00818   
...         ...        ...       ...        ...  ...        ...        ...   
1256  180.40022  75.807360  0.873704  185.60863  ...  174.58090  164.83165   
1257  180.40933  75.211730  0.881829  186.24004  ...  173.90363  165.46541   
1258  180.41914  75.214160  0.875192  185.61460  ...  175.85678  167.40865   
1259  180.41931  75.212410  0.871733  185.61563  ...  173.90488  168.68996   
1260  181.04074  75.212470  0.861892  185.61432  ...  176.50703  168.72090   

      score_22       x_23       y_23  score_23       x_24       y_24  \
0     0.531282  173.87663  168.70683  0.524592  179.09890  168.04233   
1     0.516036  172.61047  168.72954  0.525205  179.10825  168.68027   
2     0.544642  173.24898  169.33330  0.566953  179.11185  168.67523   
3     0.504813  173.25194  169.33595  0.529983  179.11575  168.67534   
4     0.542894  171.96147  169.33696  0.546907  179.12080  168.69398   
...        ...        ...        ...       ...        ...        ...   
1256  0.434457  177.79013  168.03980  0.543797  171.95619  168.69844   
1257  0.361645  177.14716  167.41610  0.452555  172.59816  168.69371   
1258  0.338161  178.44717  168.70552  0.470239  171.30334  169.36182   
1259  0.340301  177.14890  169.35510  0.439229  170.67596  169.99667   
1260  0.390068  178.45741  169.37827  0.523028  170.67284  169.99966   

      score_24  angle  
0     0.621106    0.0  
1     0.694225    0.0  
2     0.715459    0.0  
3     0.694016    0.0  
4     0.684557    0.0  
...        ...    ...  
1256  0.720516 -180.0  
1257  0.740589 -180.0  
1258  0.730980 -180.0  
1259  0.737725 -180.0  
1260  0.740516 -180.0  

[1261 rows x 76 columns]

In [206]:
x_list = []
y_list = []
for j in range(25):
    x_list.append(f"x_{j}")
for j in range(25):
    y_list.append(f"y_{j}")
df_train_x = df_train[x_list]
df_train_y = df_train[y_list]
df_train_x

x_0        x_1        x_2        x_3        x_4        x_5  \
0     179.76530  180.39920  169.99663  166.10310  164.82419  190.81128   
1     179.77000  180.40907  170.00713  166.11751  165.46109  191.43814   
2     179.78280  180.40228  169.99840  165.47404  164.80490  191.43048   
3     180.40729  180.39053  169.37404  164.81367  166.75166  191.43178   
4     181.04353  181.68724  170.66028  166.76718  168.68036  192.72653   
...         ...        ...        ...        ...        ...        ...   
1256        NaN  169.38786  180.40022  185.60863  186.25404  158.98273   
1257        NaN  169.38457  180.40933  186.24004  185.58725  158.96857   
1258        NaN  169.39172  180.41914  185.61460  184.94917  158.97491   
1259        NaN  169.99731  180.41931  185.61563  184.94273  158.98738   
1260        NaN  170.00874  181.04074  185.61432  184.31120  159.60861   

            x_6        x_7        x_8        x_9  ...       x_15       x_16  \
0     195.97879  196.62668  180.42313  173.90170  ...  178.44480  182.98984   
1     195.98444  198.57454  181.06203  173.92336  ...  178.45024  182.99370   
2     195.37273  199.22394  181.70341  173.93060  ...  178.46288  183.62692   
3     196.63023  198.58205  182.33812  174.53508  ...  179.07227  183.64801   
4     197.29126  197.93796  181.71033  174.55400  ...  179.10281  184.26704   
...         ...        ...        ...        ...  ...        ...        ...   
1256  153.79100  153.13586  169.39542  178.43437  ...        NaN        NaN   
1257  153.76251  151.82414  170.00380  178.44987  ...        NaN        NaN   
1258  153.75777  151.16260  169.39333  178.43573  ...        NaN        NaN   
1259  153.76659  151.16554  169.39284  178.43147  ...        NaN        NaN   
1260  153.75851  149.24560  169.38715  178.43324  ...        NaN        NaN   

           x_17       x_18       x_19       x_20       x_21       x_22  \
0     174.53069  186.24223  184.93248  188.84350  184.94336  175.84912   
1     174.53311  186.23615  186.89835  190.15033  184.96764  175.20096   
2     174.53241  186.25060  189.46222  191.43169  185.58693  175.85600   
3     174.52913  186.25266  188.84248  190.81580  185.61894  176.49518   
4     174.57423  186.90643  184.31430  188.85396  189.46664  174.53969   
...         ...        ...        ...        ...        ...        ...   
1256  175.86460  165.45280  162.85277  158.95595  165.47086  174.58090   
1257  175.84778  164.82117  162.86470  158.98105  164.82735  173.90363   
1258  175.86821  164.81854  162.85820  158.95226  164.16780  175.85678   
1259  175.86084  164.81796  164.17516  159.61768  164.14131  173.90488   
1260  176.49713  165.45596  166.76100  160.27415  163.52806  176.50703   

           x_23       x_24  
0     173.87663  179.09890  
1     172.61047  179.10825  
2     173.24898  179.11185  
3     173.25194  179.11575  
4     171.96147  179.12080  
...         ...        ...  
1256  177.79013  171.95619  
1257  177.14716  172.59816  
1258  178.44717  171.30334  
1259  177.14890  170.67596  
1260  178.45741  170.67284  

[1261 rows x 25 columns]

In [207]:
np_train_x = np.array(df_train_x)
for i,train_x in enumerate(np_train_x):
    df_train_x[i:i+1] = (df_train_x[i:i+1] - np.nanmin(train_x))/(np.nanmax(train_x) - np.nanmin(train_x))

In [208]:
df_train_x

x_0       x_1       x_2       x_3       x_4       x_5       x_6  \
0     0.469809  0.489742  0.162643  0.040214  0.000000  0.817140  0.979628   
1     0.432118  0.451417  0.137287  0.019823  0.000000  0.784486  0.921781   
2     0.435163  0.453161  0.150890  0.019441  0.000000  0.773571  0.888108   
3     0.461782  0.461285  0.135049  0.000000  0.057391  0.788255  0.942200   
4     0.458004  0.478655  0.124896  0.000000  0.061377  0.832810  0.979253   
...        ...       ...       ...       ...       ...       ...       ...   
1256       NaN  0.490727  0.823245  0.980512  1.000000  0.176546  0.019782   
1257       NaN  0.510242  0.830581  1.000000  0.981032  0.207591  0.056322   
1258       NaN  0.529116  0.849197  1.000000  0.980685  0.226759  0.075327   
1259       NaN  0.546639  0.849164  1.000000  0.980467  0.227048  0.075502   
1260       NaN  0.570907  0.874244  1.000000  0.964169  0.284943  0.124088   

      x_7       x_8       x_9  ...      x_15      x_16      x_17      x_18  \
0     1.0  0.490494  0.285434  ...  0.428288  0.571202  0.305212  0.673471   
1     1.0  0.471136  0.255554  ...  0.392262  0.529471  0.273968  0.627390   
2     1.0  0.490964  0.265135  ...  0.396815  0.546849  0.282620  0.623077   
3     1.0  0.518960  0.287885  ...  0.422247  0.557751  0.287709  0.634884   
4     1.0  0.479396  0.249812  ...  0.395743  0.561419  0.250461  0.646094   
...   ...       ...       ...  ...       ...       ...       ...       ...   
1256  0.0  0.490956  0.763886  ...       NaN       NaN  0.686292  0.371909   
1257  0.0  0.528234  0.773646  ...       NaN       NaN  0.698039  0.377646   
1258  0.0  0.529163  0.791627  ...       NaN       NaN  0.717102  0.396376   
1259  0.0  0.529093  0.791462  ...       NaN       NaN  0.716843  0.396296   
1260  0.0  0.553815  0.802548  ...       NaN       NaN  0.749312  0.445723   

          x_19      x_20      x_21      x_22      x_23      x_24  
0     0.632287  0.755265  0.632629  0.346669  0.284646  0.448855  
1     0.647388  0.745596  0.589082  0.294136  0.215906  0.412133  
2     0.716386  0.773606  0.603795  0.321075  0.245332  0.415670  
3     0.711577  0.770014  0.616117  0.345930  0.249887  0.423535  
4     0.562935  0.708573  0.728229  0.249352  0.166640  0.396321  
...        ...       ...       ...       ...       ...       ...  
1256  0.293401  0.175737  0.372454  0.647531  0.744433  0.568278  
1257  0.320798  0.207954  0.377826  0.641549  0.735794  0.603617  
1258  0.339475  0.226102  0.377488  0.716771  0.791959  0.584603  
1259  0.377637  0.245344  0.376654  0.660066  0.754232  0.566339  
1260  0.481606  0.303243  0.392713  0.749585  0.803212  0.589167  

[1261 rows x 25 columns]

In [209]:
np_train_y = np.array(df_train_y)
for i,train_y in enumerate(np_train_y):
    df_train_y[i:i+1] = (df_train_y[i:i+1] - np.nanmin(train_y))/(np.nanmax(train_y) - np.nanmin(train_y))

In [210]:
df_tmp = pd.concat([df_train_x,df_train_y],axis=1)
df_tmp["angle"] = df_train["angle"]

In [211]:
df_tmp["angle"].unique()

array([   0.,   30.,   60.,   90.,  -90., -120., -150., -180.])

In [212]:
df_inv = df_tmp.copy()
flip_vec = (0, 1, 5, 6, 7, 2, 3, 4, 8, 12, 13, 14, 9, 10, 11,16, 15, 18, 17, 22, 23, 24, 19, 20, 21)
for i,inv in enumerate(flip_vec):
    df_inv[f"x_{inv}"] = df_tmp[f"x_{i}"]
    df_inv[f"x_{inv}"] = df_tmp[f"x_{i}"]
df_inv["angle"] = -df_tmp["angle"]
df_inv

x_0       x_1       x_2       x_3  x_4       x_5       x_6  \
0     0.469809  0.489742  0.817140  0.979628  1.0  0.162643  0.040214   
1     0.432118  0.451417  0.784486  0.921781  1.0  0.137287  0.019823   
2     0.435163  0.453161  0.773571  0.888108  1.0  0.150890  0.019441   
3     0.461782  0.461285  0.788255  0.942200  1.0  0.135049  0.000000   
4     0.458004  0.478655  0.832810  0.979253  1.0  0.124896  0.000000   
...        ...       ...       ...       ...  ...       ...       ...   
1256       NaN  0.490727  0.176546  0.019782  0.0  0.823245  0.980512   
1257       NaN  0.510242  0.207591  0.056322  0.0  0.830581  1.000000   
1258       NaN  0.529116  0.226759  0.075327  0.0  0.849197  1.000000   
1259       NaN  0.546639  0.227048  0.075502  0.0  0.849164  1.000000   
1260       NaN  0.570907  0.284943  0.124088  0.0  0.874244  1.000000   

           x_7       x_8       x_9  ...  y_16      y_17      y_18      y_19  \
0     0.000000  0.490494  0.774757  ...   0.0  0.011875  0.006129  0.994047   
1     0.000000  0.471136  0.725480  ...   0.0  0.011819  0.006036  0.999595   
2     0.000000  0.490964  0.717583  ...   0.0  0.011676  0.006123  0.994037   
3     0.057391  0.518960  0.731356  ...   0.0  0.017233  0.011520  0.999638   
4     0.061377  0.479396  0.728875  ...   0.0  0.011524  0.005955  0.994466   
...        ...       ...       ...  ...   ...       ...       ...       ...   
1256  1.000000  0.490956  0.313052  ...   NaN  0.000000  0.000010  1.000000   
1257  0.981032  0.528234  0.339287  ...   NaN  0.000000  0.005999  1.000000   
1258  0.980685  0.529163  0.357957  ...   NaN  0.000000  0.006042  0.993987   
1259  0.980467  0.529093  0.357937  ...   NaN  0.000000  0.005928  0.976134   
1260  0.964169  0.553815  0.391519  ...   NaN  0.000000  0.011835  0.964211   

          y_20      y_21      y_22      y_23      y_24  angle  
0     0.994103  0.970747  1.000000  0.994148  0.988130   -0.0  
1     0.993942  0.982113  1.000000  0.994078  0.993632   -0.0  
2     0.993584  0.970360  1.000000  0.999494  0.993536   -0.0  
3     0.993901  0.982071  1.000000  0.999534  0.993587   -0.0  
4     0.999910  0.988337  1.000000  0.993956  0.988167   -0.0  
...        ...       ...       ...       ...       ...    ...  
1256  0.994041  0.897100  0.951749  0.981687  0.987833  180.0  
1257  0.993903  0.945574  0.963917  0.982012  0.993864  180.0  
1258  0.987712  0.951482  0.981664  0.993839  1.000000  180.0  
1259  0.981886  0.969926  0.987877  0.994048  1.000000  180.0  
1260  0.958153  0.976004  0.988207  0.994269  1.000000  180.0  

[1261 rows x 51 columns]

In [213]:
df_inv = df_inv[df_inv["angle"] != 0.0]
df_inv = df_inv[df_inv["angle"] != 180.0]
df_inv = df_inv[df_inv["angle"] != 90.0]
df_inv = df_inv[df_inv["angle"] != -90.0]


df_inv["angle"].unique()

array([-30., -60., 120., 150.])

In [214]:
df_final = pd.concat([df_inv,df_tmp]) 
df_final["angle"].unique()


array([ -30.,  -60.,  120.,  150.,    0.,   30.,   60.,   90.,  -90.,
       -120., -150., -180.])

In [215]:
df_final.groupby("angle")["angle"].count()

angle
-180.0    132
-150.0    206
-120.0    178
-90.0     174
-60.0     132
-30.0     187
 0.0      106
 30.0     187
 60.0     132
 90.0     146
 120.0    178
 150.0    206
Name: angle, dtype: int64

In [216]:
df_final["angle"] = df_final["angle"].replace(0,0).replace(30,1).replace(60,2).replace(90,3).replace(120,4).replace(150,5).replace(-180,6).replace(-150,7).replace(-120,8).replace(-90,10).replace(-60,11).replace(-30,12)

In [217]:
# df_final = df_tmp.fillna(-1)
df_final.to_csv("./input/df_test_final.csv",index=False)

In [218]:
df_final["angle"].unique()

array([12., 11.,  4.,  5.,  0.,  1.,  2.,  3., 10.,  8.,  7.,  6.])